name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout tentacle
        uses: actions/checkout@v4
        with:
          repository: nervosnetwork/tentacle
          path: ../nervosnetwork/tentacle
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: cargo test --features ws,quic -- --nocapture

