name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout tentacle
        run: |
          mkdir -p ../../nervosnetwork
          git clone --depth 1 https://github.com/nervosnetwork/tentacle ../../nervosnetwork/tentacle
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: cargo test --features ws,quic -- --nocapture
